#!/bin/bash

#build the tunnel to remote_ip via host
ssh -N -L <local_port>:<remote_ip>:<remote_port user@host &

#connect to host, via local port
ssh -p <local_port> <user>@localhost

#tunnel a remote port to another machine while using an existing tunnel
ssh -p6934 root@localhost -L localhost:8080:192.168.1.1:80

