#!/usr/bin/expect

if {$argc != 2} {
        send_user "\tusage: $argv0 <ip-address> \"<multi word command>\"\n"
        exit
}

set IPADDRESS [lindex $argv 0]
set COMMAND [lindex $argv 1]

# security: write password to root only readable file in e.g. /root/authfiles
# so you may use this password here by:
#
#set PASSWORD_DIR       /root/authfiles
#set PASSWORD_FILE      "pwd-${IPADDRESS}"
#set status [catch { exec cat ${PASSWORD_DIR}${PASSWORD_FILE} } PASSWORD]
#
# alternatively set password simply here
set PASSWORD "<PASSWORD>"

spawn /usr/bin/ssh <user>@${IPADDRESS}

while (1) {
        expect {
                "password:" { 
                        send "${PASSWORD}\n" 
                        break 
                }
                # this is useful, if ssh connects first time to IPADDRESS
                "connecting (yes/no)?" { send "yes\n" }
        }
}

expect "<what to expect" { send "${COMMAND}\n" }
expect "<what to expect" { send "exit\n" }
#expect "ES-2024PWR#" { send "${COMMAND}\n" }
#expect "ES-2024PWR#" { send "exit\n" }
